version: '3'
services:
  fastify-server:
    build:
      context: ./server
    ports: 
      - 3333:3333
    command:
      export DATABASE_URL="file:/app/server/prisma/dev.db"
      npm run start
    depends_on:
      - react-server
  
  react-server:
    build:
      context: ./web
    ports:
      - 5173:5173
    command:
      npm run start